config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :providers

  resources :users do
     resources :favorites do
     end
     resources :comparisons
   end

  get "/learn" => "welcome#learn"
  get "/logout" => "sessions#destroy", as: :logout
  get "/auth/:provider/callback" => "sessions#create"
  get '/login' => "welcome#login"

  post '/' => "welcome#search_term", as: :search_term

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :provider

  validates :name, presence: true

  def yelp_info
    @yelp_info ||= Yelp.client.business(provider_id).business
  end

  def name
    yelp_info.name
  end

  def display_phone
    if yelp_info.display_phone
      yelp_info.display_phone[3..-1]
    end
  end

  def image_url
    yelp_info.image_url
  end

  def rating_img_url
    yelp_info.rating_img_url
  end

  def category
    yelp_info.categories[0][0]
  end

  def bus_url
    yelp_info.url
  end

  def street
    yelp_info.location.display_address[0]
  end

  def city
    yelp_info.location.city
  end

  def state_code
    yelp_info.location.state_code
  end

  def postal_code
    yelp_info.location.postal_code
  end

  # def add_note
  #
  # end
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  has_many :favorites
  has_many :users, through: :user_favorites
  has_many :comparisons, through: :provider_comparisons

  # validates :name, presence: true

  self.primary_key = "yelp_id"
  # attr_reader :name, :phone, :url, :image_url, :rating, :rating_img_url, :location
  #
  # def initialize(data)
  #   @name               = data.business.name
  #   @phone              = data.business.phone
  #   @url                = data.business.url
  #   @image_url          = data.business.image_url
  #   @rating_img_url     = data.business.rating_img_url
  #   @rating             = data.business.rating
  #   @location           = data.business.location.display_address
  # end

  def yelp_info
    @yelp_info ||= Yelp.client.business(id).business
  end

  def name
    yelp_info.name
  end

  def display_phone
    yelp_info.display_phone[3..-1]
  end

  def image_url
    yelp_info.image_url
  end

  def rating_img_url
    yelp_info.rating_img_url
  end

  def category
    yelp_info.categories[0][0]
  end

  def bus_url
    yelp_info.url
  end

  def street
    yelp_info.location.display_address[0]
  end

  def city
    yelp_info.location.city
  end

  def state_code
    yelp_info.location.state_code
  end

  def postal_code
    yelp_info.location.postal_code
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites
  has_many :providers,  through: :user_favorites
  validates :uid, :provider, presence: true
   #:name

   def self.find_or_create_from_omniauth(auth_hash)
     # Find or create a user

     user = self.find_by(uid: auth_hash["uid"], provider: auth_hash["provider"])
     if !user.nil?
       return user
     else
       user = User.new
       user.provider  = auth_hash["provider"]
       user.uid       = auth_hash["uid"]
       user.name      = auth_hash["info"]["name"]
       user.email     = auth_hash["info"]["email"]
       user.image     = auth_hash["info"]["image"]
     end
       if user.save
         return user
       else
         return nil
       end
     end

    def favorited?(provider)
      !Favorite.find_by(user: self, provider: provider).nil?
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    # if session[:user_id] && !!User.exists?(session[:user_id])
      @user = User.find_by(id: session[:user_id])

  end

  def require_login
    if current_user.nil?
      flash[:error] = "You must be logged in to view this section"
      redirect_to root_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
# before_action :require_login

  def index
    @user = params[:user_id]
    @provider = Provider.where(yelp_id: (params[:provider_id]))
    @favorites = Favorite.where(user_id: @user)

  end

  def create
    @provider = Provider.find_or_create_by(yelp_id: (params[:provider_yelp_id]))
    @user = User.find(params[:user_id])
    if Favorite.find_by(user: @user, provider: @provider)
      flash[:notice] = 'This provider was already in your list'
      return render :index
    end

    @favorite = Favorite.create({
      user_id:  @user.id,
      provider_id: @provider.id
      })

    if @favorite && @provider
      flash[:notice] = 'This provider was added to your list'
      redirect_to user_favorites_path(@user.id, @provider.id)
    else
      flash[:notice] = 'This provider was not added to your list'
      render :index
    end
  end

  def update
    @favorite = Favorite.find(params[:id])
    if @favorite.update(notes: params[:favorite][:notes])
      redirect_to user_favorites_path, notice: 'Note was successfully updated.'
    else
      render :user_favorites_path
    end
  end

  def destroy
    @favorite = Favorite.where(user_id: params[:user_id], provider_id: params[:id])
    @user = User.find(params[:user_id])
    @user.favorites.delete(@favorite)
    redirect_to user_favorites_path
  end
    # @provider = Provider.where(yelp_id: (params[:provider_id]))
    # current_user.favorites << @provider
    # flash[:notice] = 'This provider was added to your list'
    # redirect_to root_path
    # rescue
    # flash[:notice] = 'This provider was not added to your list'
    # redirect_to user_favorites_path(current_user.id)
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :must_be_logged_in
  # attr_reader :name, :phone, :url, :image_url, :rating, :rating_img_url, :location
  #
  # def initialize(data)
  #   @name               = data.business.name
  #   @phone              = data.business.phone
  #   @url                = data.business.url
  #   @image_url          = data.business.image_url
  #   @rating_img_url     = data.business.rating_img_url
  #   @rating             = data.business.rating
  #   @location           = data.business.location.display_address
  # end
  #
  # def self.find_provider(params[:id])
  #   business = Yelp.client.business(params[:id])
  #   return self.new(business)
  # end

  def show
    @result = Provider.find(params[:id])
    # @result = Provider.create(params[:id])
    render :show
  end


  private

    def providers_params
      params.permit(providers:[:id, :yelp_id])
    end

    def must_be_logged_in
      if current_user.nil?
        redirect_to '/login'
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth_hash = request.env['omniauth.auth']
    # if auth_hash["uid"].nil?

    user = User.find_or_create_from_omniauth(auth_hash)
      if user
        session[:user_id] = user.id
        redirect_to root_path
      else
        flash[:notice] = "sorry #{auth_hash.inspect}"
        redirect_to root_path
      end
    end

    def destroy
      session.delete :user_id
      redirect_to root_path
    end
end

app/controllers/welcome_controller.rb
require 'yelp'

class WelcomeController < ApplicationController
  def index

  end

  def search_term
    care_types = {
      "Home Health Care" => "homehealthcare",
      "Assisted Living Facilities" => "assistedliving",
      "Retirement Homes" => "retirement_homes"
    }

    query = params[:category]

    if query
      converted_search_query = care_types[query]
    end

    all_data = {
     limit: 20,
     category_filter: converted_search_query
    }

    if all_data && params[:city].present?
      @results = Yelp.client.search(params[:city], all_data)
      render :index
    else
      flash[:notice] = "sorry - please enter valid data"
      redirect_to root_path
    end
  end

  def learn
    render :learn
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/favorites/index.html.erb
  <div>
    <span class="black-text">
      <center><h3><%= current_user.name %>'s Saved Providers</h3></center>
    </span>
<!--
    <div id="reacttest">This is react playground</div> -->

    <% current_user.favorites.each do |favorite| %>
    <div class="container">
      <h4 class="header"><strong><%= favorite.name %></strong></h4>
        <div class="card horizontal">
        <div class="card-image">
          <div style="padding-left: 1rem; padding-top: 1rem;">
          <%= image_tag favorite.image_url %>
          <%= image_tag favorite.rating_img_url %>
          <div class="card-action">
          <%= link_to 'Delete from favorites'.html_safe, user_favorite_path(current_user.id, favorite.provider_id), method: :delete, class: "button info" %><br>
          </div>
        </div>
        </div>

        <!-- <div class="col s5 m5"> -->
          <ul>
            <span class="black-text">
            <li><%= favorite.street%></li>
            <li><%= favorite.city%>, <%= favorite.state_code %> <%=  favorite.postal_code%></li>
            <li><%= favorite.display_phone%></li><br>
            <li><%= "Average Monthly Cost: $" + favorite.provider.average_cost.to_s%></li>
            <% if favorite.category == "Home Health Care" %>
              <li><%= "Available In-home attendants: " + favorite.provider.bed_count.to_s%></li>
            <% else %>
              <li><%= "In-facility Bed Count: " + favorite.provider.bed_count.to_s%></li>
            <% end %>
          </span>
          </ul>
        <!-- </div> -->

          <span class="black-text">
            <div class="notes">
            <% if favorite.notes %>
              <p><%= simple_format("Notes: " + favorite.notes) %></p>
            <% end %><br>
          </span>

            <section class="notesshow black-text">
            <%= form_for(favorite, url: user_favorite_path(favorite.user_id, favorite.id), html: {method: "patch"}) do |f| %>
              <fieldset>
                <h8><i class="material-icons">mode_edit</i>Add a note to log:</h8>
                <div class="form-group">
                <!-- <%= f.label :name %> -->
                <%= f.text_area :notes, size: "40x5", label: false, placeholder: "enter any notes", :required => true %>
                </div>
                <%= f.hidden_field :user_id, :value => session[:user_id] %>
              </fieldset>
              <button class="waves-effect waves-teal btn-flat"><%= f.submit class: "button info" %>
                <i class="material-icons right">send</i>
              </button>
            <% end %>
          </section>
          <button class="button-hide">Hide</button>
          <button class="button-show">Add/Edit notes</button>
          </div>

        </div>
      </div><br>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeaconSeniorResources</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script>
  $(document).ready(function(){
    $(".button-hide").click(function(){
      var notesDiv = $(this).parents(".notes");
        $(".notesshow", notesDiv).hide();
    });
    $(".button-show").click(function(){
      var notesDiv = $(this).parents(".notes");
        $(".notesshow", notesDiv).show();
    });
  });
  </script>

  <!-- <script>
  $(document).ready(function(){
    $("#flip").click(function(){
      $("#panel").slideToggle("slow");
    });
  });
  </script> -->

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"> -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <!--Import jQuery before materialize.js-->
  <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script type="text/javascript" src="js/materialize.min.js"></script> -->

  <nav>
    <div class="nav-wrapper  indigo darken-1">
    <div style="opacity: .7;"></div>
      <a href="#" class="brand-logo">Beacon Senior Resources</a>
      <div class="right hide-on-med-and-down">
        <div style="display: inline-block; line-height: 30px; text-align: right; margin-right: .75rem;">
          <% if current_user %>
          <%= current_user.name %><br>
          <%= link_to "Sign out", logout_path, id: "sign_out" %>
          <% else %>
          <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
          <% end %>
        </div>
        <% if current_user %>
        <div style="display: inline-block;">
          <%= image_tag current_user.image, class: "picprofile" %>
        </div>
        <%end%>
      </div>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Learn more about Senior Care", learn_path %></li>
        <li><%= link_to "My Saved Providers", user_favorites_path(current_user.id) if current_user %></li>
      </ul>
    </div>
  </nav><br>

  <% if !flash.empty? %>
   <div class="alert alert-info">
     <% flash.each do |key, msg| %>
       <%= content_tag :div, msg, :id => key %>
     <% end %>
   </div>
 <% end %>

    <%= yield %>
</body>

<!-- <div class="mastfoot">
  <div class="inner">
    <p>© 2016 Beacon Senior Resources ~</p>
  </div>
</div> -->
</html>

app/views/layouts/copy_app.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeaconSeniorResources</title>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"> -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>

<% if current_user %>
  <nav class="navbar navbar-default">
     <div class="container-fluid">
         <!-- Brand and toggle get grouped for better mobile display -->
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
        <%= image_tag("LIGHTHOUSE-BEACON.png", class: "img-responsive", style: "height: 11rem; width: 11rem; margin: 13px")%>
       </div>
      <div>
        <h1 class="masthead-brand"><a href="/">Beacon Senior Resources</a>
          <small>Helping families find the right senior care</small></h1>
      </div>

        <ul class="nav navbar-nav navbar-mid">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Learn more about Senior Care", learn_path %></li>
          <li><%= link_to "My Saved Providers", user_favorites_path(current_user.id) if current_user %></li>
        </ul>

      <div class ="google_login">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <p class="name"><%= current_user.name %></p>
            <%= image_tag current_user.image, class: "picprofile" %>
            <p class="name"><%= link_to "Sign out", logout_path, id: "sign_out" %></p>
          <% end %>

          <% unless current_user %>
            <li><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
          <% end %>
        </ul>
      </div>
    </div><!-- /.container-fluid -->
  </nav>
    <% if flash[:notice] -%>
    <div class="alert alert-warning" role="alert">
      <p class='notice'><%= flash[:notice] %></p>
    </div>
    <% end %>
  <% else %>
  <div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand">Beacon Senior Resources</h3>

          <ul class="nav masthead-nav">
            <li class="active">
              <!-- Validation -->
              <li><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
            </li>
          </ul>
        </div>
      </div>
    </div>
   </div>
  </div>


  <% end %>
</header>

<body>
    <%= yield %>
</body>

<!-- <div class="mastfoot">
  <div class="inner">
    <p>© 2016 Beacon Senior Resources ~</p>
  </div>
</div> -->
</html>

app/views/providers/index.html.erb
<h1> testing providers index</h1>

<% if @results == nil %>
<% elsif @results.businesses.length == 0 %>
  <h3> Sorry, there are no results for that search. </h3>
<% else %>
<div>
  <ul>
    <% @results.businesses.each do |business|%>
     <li><%= business.name %><br>
     <%= image_tag business.rating_img_url %><br>
     <%= "Category: " + business.categories[0][0] %><br>
     <% business.location.display_address.each do |line| %>
      <%= line %><br>
     <% end %><br>
     <%= business.phone %><br>
     <%= image_tag business.image_url %>
     <%= link_to "see reviews", business.url %></p>
     <%= button_to "show more details", provider_path(business.id), method: :get %>
    <% end %>
  </ul>
</div>
<% end %>

app/views/providers/show.html.erb
<center><div class="container"></center>
  <% if @result %>
    <div class="row">
        <center><div class="col s12 m6 offset-m3">
          <div class="card indigo lighten-3">
            <div class="card-content white-text">
              <span class="card-title"><%= @result.name %></span>
              <ul>
                <%= image_tag @result.image_url %><br>
                <%= image_tag @result.rating_img_url %><br>
                <%= @result.street %><br>
                <%= @result.city %>, <%= @result.state_code %> <%= @result.postal_code %><br>
                <%= @result.display_phone %><br>
                <%= "Category: " + @result.category %><br>

                <% unless @result.bed_count == nil %>
                <li><%= "Available In-home attendants or In-facility Bed Count: " + @result.bed_count.to_s%></li>
                <% end %>

                <% unless @result.average_cost == nil %>
                <li><%= "Average Monthly Cost: $" + @result.average_cost.to_s%></li>
                <% end %>

                <div class="card-action">
                <%= link_to "See More Reviews on Yelp", @result.bus_url %></p>
                <div class="divider"></div>
                <% if current_user %>
                  <%= link_to 'See my favorites'.html_safe, user_favorites_path(current_user.id), method: :get, class: "button info" %><br>
                <% end %>
                <div class="divider"></div>
                <% if current_user && (!current_user.favorited?(@result)) %>
                  <%= form_tag user_favorites_path(current_user.id), method: :post do %>
                    <%= hidden_field_tag 'provider_yelp_id', @result.id %>
                    <%= button_tag id: "no_float", class: "waves-effect waves-teal btn-flat" do %>
                      <i class="material-icons right">send</i>Add to My Provider List
                    <% end %>

                  <% end %>
                <% else %>
                <div class="divider"></div>
                  <%= link_to '<i class="fi-trash"></i> Delete from favorites'.html_safe, user_favorite_path(current_user.id, @result.id), method: :delete, class: "button info" %>
                <% end %>
              </div>
              </ul>
          </div>
        </div>
    </div>
  </div></center>
<% end %>

app/views/welcome/index.html.erb
<div class="landing_body">
    <% unless current_user %>
      <h2 style="text-align: center; color: black;">Welcome!</h2>
    <% end %>

    <div style="width: 50%; margin: 0 auto;">
    <h4 style="text-align: center; color: black;">Search for a provider in your area</h4>

      <div class="row">
          <div class="col s12 m10 offset-m1">
            <div style="opacity: .7;">
            <div class="card-panel indigo lighten-3">
              <span class="white-text">
                <h4 class="search">Enter your search term:</h4>
                  <%= form_tag search_term_path, method: "post", class: "" do  %>
                    <%= text_field_tag :city, nil, class: 'form-control', placeholder: 'city' %><br>

                    <p><%= radio_button_tag 'category', 'Home Health Care', false, class: ""%>
                    <%= label_tag("category_Home_Health_Care", "Home Health Care", class: "white-text") %></p>

                    <p><%= radio_button_tag 'category', "Assisted Living Facilities", false, class: ""%>
                    <%= label_tag("category_Assisted_Living_Facilities", "Assisted Living Facilities", class: "white-text") %></p>

                    <p><%= radio_button_tag 'category', "Retirement Homes", false, class: ""%>
                    <%= label_tag("category_Retirement_Homes", "Retirement Homes", class: "white-text") %></p>

                    <span class="input-group-btn">
                      <%= submit_tag "Search", class: 'btn btn-default'%>
                    </span>
                  <% end %>
              </span>
            </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

<% if @results == nil %>
<% elsif @results.businesses.length == 0 %>
  <h3> Sorry, there are no results for that search. </h3>
<% else %>
<div class="row">
  <% @results.businesses.each do |business|%>
  <!-- <div class="container"> -->

  <div class="col s5">
    <h4 class="header"><%= business.name %></h4>
    <!-- <h4><%= business.id %></h4> -->
      <div class="card horizontal">
      <div class="card-image">
        <div style="padding: 1rem;">
        <%= image_tag business.image_url %>
        <%= image_tag business.rating_img_url %>
        <span class="black-text">
        <%= "Category: " %><br>
        <%= business.categories[0][0] %>
        </span>
      </div>
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <span class="black-text">
          <p>
          <%= business.location.address[0] %><br>
          <%= business.location.city %>, <%= business.location.state_code %> <%= business.location.postal_code %><br>
            <% if business.display_phone %>
              <%= "tel: (#{business.display_phone[3..5]}) #{business.display_phone[7..-1]}" %>
            <% end %>
            <span class="glyphicon glyphicon-phone-alt">&nbsp;</span>
          </p>
        </span>
        </div>
        <div class="card-action">
          <%= link_to "see reviews", business.url %>
          <div class="divider"></div>
          <%= link_to "show more details", provider_path(business.id), method: :get %>

        </div><br>
      </div>
      </div>
  </div>
  <!-- </div> -->
  <% end %>
</div>
<% end %>

<!--

<% if @results == nil %>
<% elsif @results.businesses.length == 0 %>
  <h3> Sorry, there are no results for that search. </h3>
<% else %>
<div>
  <ul>
    <% @results.businesses.each do |business|%>
     <li><%= business.name %><br>
     <li><%= business.id %><br>
       <%= image_tag business.rating_img_url %><br>
       <%= "Category: " + business.categories[0][0] %><br>
       <% business.location.display_address.each do |line| %>
       <%= line %><br>
       <% end %><br>
       <%= business.phone %><br>
       <%= image_tag business.image_url %>

     <%= link_to "see reviews", business.url %></p>
     <%= button_to "show more details", provider_path(business.id), method: :get %>
    <% end %>
  </ul>
</div>
<% end %> -->

app/views/welcome/learn.html.erb
  <center><div class="container"></center>
    <center><div class="col s7 offset-s2">
      <%= image_tag("senior-living-diagram.jpg", alt: "diagram") %>
    </div></center>
  </div>

app/views/welcome/login.html.erb
<center>
  <h2>Login to see more</h2>

  <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
</center>